#!/usr/bin/env python
import argparse
import json
import logging

try:
    from . import experiment_utils as exp
except ImportError:
    import experiment_utils as exp


LOGGER = logging.getLogger("compare_update_capacity")


def parse_args():
    parser = argparse.ArgumentParser(description="Compare repeated merged LoRA updates with one-shot LoRA memory.")
    parser.add_argument("--runtime-config", type=str, default=str(exp.DEFAULT_RUNTIME_CONFIG_PATH), help="MemoryTest runtime config with model/checkpoint paths.")
    parser.add_argument("--facts-path", type=str, default="MemoryTest/json_data/semantic_facts.json", help="Fact JSON generated by generate_capacity_data.py.")
    parser.add_argument("--output-path", type=str, default="MemoryTest/results/update4_merged_vs_single20.json", help="Where to save comparison results.")
    parser.add_argument("--num-updates", type=int, default=4, help="Number of merged LoRA updates for condition A.")
    parser.add_argument("--facts-per-update", type=int, default=2, help="Facts per update for condition A.")
    parser.add_argument("--save-loras", action="store_true", help="Save A and B generated LoRA dictionaries next to the result JSON.")
    parser.add_argument("--log-context", action="store_true", help="Print the exact A/B contexts before generating LoRA.")
    parser.add_argument("--merge-method", choices=["average", "sum", "concat"], default="average", help="How to merge LoRAs across repeated updates.")
    return parser.parse_args()


def main():
    args = parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")

    total_facts = args.num_updates * args.facts_per_update
    output_path = exp.resolve_path(args.output_path)

    facts, facts_path = exp.read_json_rows(args.facts_path, total_facts)
    facts = facts[:total_facts]
    fact_chunks = exp.chunk_rows(facts, args.facts_per_update, args.num_updates)

    runtime_args, device, cfg, metanetwork, metalora, tokenizer = exp.bootstrap_runtime(args.runtime_config)

    lora_a, contexts_a = exp.generate_merged_lora(
        fact_chunks,
        metanetwork,
        tokenizer,
        metalora,
        cfg,
        device,
        log_context=args.log_context,
        condition_label=f"A_{args.merge_method}_merge",
        merge_method=args.merge_method,
    )
    LOGGER.info("B/single: generating LoRA from all %s facts at once", total_facts)
    context_b = exp.build_context(facts)
    if args.log_context:
        LOGGER.info("B/single context:\n%s", context_b)
    lora_b = exp.generate_context_lora(context_b, metanetwork, tokenizer, metalora, cfg, device)

    if args.save_loras:
        exp.save_lora_snapshot(output_path.with_name(output_path.stem + f"_A_{args.merge_method}_lora.pt"), lora_a)
        exp.save_lora_snapshot(output_path.with_name(output_path.stem + "_B_single_lora.pt"), lora_b)

    result_a = exp.evaluate_lora(f"A_{args.num_updates}x{args.facts_per_update}_{args.merge_method}_lora", facts, lora_a, metanetwork, tokenizer, runtime_args, device)
    result_b = exp.evaluate_lora(f"B_1x{total_facts}_single_lora", facts, lora_b, metanetwork, tokenizer, runtime_args, device)

    payload = {
        "experiment": {
            "description": "A: repeated LoRA generation merged across updates; B: one-shot LoRA from the same facts.",
            "num_updates": args.num_updates,
            "facts_per_update": args.facts_per_update,
            "total_facts": total_facts,
            "facts_path": str(facts_path),
            "runtime_config": str(exp.resolve_path(args.runtime_config)),
            "merge_method": args.merge_method,
        },
        "summary": {
            result_a["label"]: exp.summarize_result(result_a),
            result_b["label"]: exp.summarize_result(result_b),
        },
        "contexts": {
            result_a["label"]: contexts_a,
            result_b["label"]: [
                {
                    "update_index": 1,
                    "num_rows": len(facts),
                    "num_facts": len(facts),
                    "fact_ids": [row["id"] for row in facts],
                    "context": context_b,
                }
            ],
        },
        "results": [result_a, result_b],
    }

    exp.write_payload(output_path, payload)
    print(json.dumps(payload["summary"], indent=2, ensure_ascii=False))
    print(f"Saved results to {output_path}")


if __name__ == "__main__":
    main()
